apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: django_app
spec:
  containers:
    - name: web
      image: cadibob/k8s_django:v1.01
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
