apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-clearsessions
  labels:
    app.kubernetes.io/name: k8s
    app.kubernetes.io/component: clearsessions
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 100
      template:
        metadata:
          labels:
            app.kubernetes.io/name: k8s
            app.kubernetes.io/component: clearsessions
        spec:
          containers:
          - name: clearsessions
            image: cadibob/k8s_django:v1.02
            imagePullPolicy: IfNotPresent
            command:
              - python
              - manage.py
              - clearsessions
            envFrom:
              - configMapRef:
                  name: env
          restartPolicy: Never
