apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
  labels:
    app.kubernetes.io/name: k8s
    app.kubernetes.io/component: migrations
spec:
  activeDeadlineSeconds: 120
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8s
        app.kubernetes.io/component: migrations
    spec:
      restartPolicy: Never
      containers:
        - name: migrations
          imagePullPolicy: IfNotPresent
          image: cadibob/k8s_django:v1.02
          command:
            - python
            - manage.py
            - migrate
          env:
            - name: DATABASE_URL
              value: postgres://postgres:OwOtBep9Frut@pg:5432/postgres
